### ISSUE TITLE
ImportError: No module named callback

### ISSUE THREAD

**Issue by snevs** [ginsys/ansible-plugins#13]
```
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
ERROR! Unexpected Exception: No module named callback
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 81, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 171, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 368, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/callback/timestamp.py", line 19, in <module>
    from ansible.callback import display
**ImportError: No module named callback**
```

**Comment by srgvg** [comment]
Most plugins are not updated to to ansible v2 I'm afraid.
